version: "3.8"

services:
  frontend:
    build: ../e-2-3/frontend/.
    ports:
      - 3000:3000
  backend:
    build: ../e-2-3/backend/.
    ports:
      - 3001:3001
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:6
